import type { Metadata } from "next";
import "./globals.css";
import { Providers } from "./providers";

export const metadata: Metadata = {
  title: "People Analytics",
  description: "Generated by create next app",
};

const LIGHT_PRESET= 'slate-mist'

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html suppressHydrationWarning data-light-preset={LIGHT_PRESET}>
      <body className="antialiased">
       <Providers>
        {children}
        </Providers>
      </body>
    </html>
  );
}
