import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { Providers } from "./providers";

const prelo = localFont({
  variable: "--font-prelo",
  display: "swap",
  src: [
    {
      path: "../public/fonts/Prelo-Light.otf",
      weight: "300",
      style: "normal",
    },
    {
      path: "../public/fonts/Prelo-Light Italic.otf",
      weight: "300",
      style: "italic",
    },
    {
      path: "../public/fonts/Prelo-Book.otf",
      weight: "400",
      style: "normal",
    },
    {
      path: "../public/fonts/Prelo-Book Italic.otf",
      weight: "400",
      style: "italic",
    },
    {
      path: "../public/fonts/Prelo-Medium.otf",
      weight: "500",
      style: "normal",
    },
    {
      path: "../public/fonts/Prelo-Medium Italic.otf",
      weight: "500",
      style: "italic",
    },
    {
      path: "../public/fonts/Prelo-Bold.otf",
      weight: "700",
      style: "normal",
    },
    {
      path: "../public/fonts/Prelo-Bold Italic.otf",
      weight: "700",
      style: "italic",
    },
    {
      path: "../public/fonts/Prelo-Black.otf",
      weight: "900",
      style: "normal",
    },
    {
      path: "../public/fonts/Prelo-Black Italic.otf",
      weight: "900",
      style: "italic",
    },
  ],
});

export const metadata: Metadata = {
  title: "People Analytics",
  description: "Generated by create next app",
};

const LIGHT_PRESET= 'slate-mist'

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html suppressHydrationWarning data-light-preset={LIGHT_PRESET}>
      <body
        className={`${prelo.variable} antialiased`}
      >
       <Providers>
        {children}
        </Providers>
      </body>
    </html>
  );
}
